### ISSUE TITLE
Add breadcrumbs to the main content area

### ISSUE THREAD

**Issue by onevision** [IronSummitMedia/startbootstrap-sb-admin-2#77]
It would be nice to include breadcrumbs in the main content area. I have tried adding the standard Bootstrap breadcrumbs, but they don't look quite right
![screen shot 2015-09-03 at 17 11 36](https://cloud.githubusercontent.com/assets/1558073/9663941/e98b7460-525e-11e5-8183-494d010c55c4.png)

**Comment by mwinandy** [comment]
+1 But with style.

**Comment by onevision** [comment]
@mwinandy its the 'style' that I need help with... Any designers out there?

**Comment by Zeromax** [comment]
Just how I do it:
```html
<div class="row">
	<div class="col-lg-12">
        <h1 class="page-header"><small>Artikel  <i class="fa fa-angle-right"></i> &nbsp;Slider  <i class="fa fa-angle-right"></i> </small> Inhaltselement ID 160 bearbeiten</h1>
    </div>
</div>
```

Inside the headline with a `<small>` tag.
It looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/1867177/9729526/46170406-5610-11e5-95e9-e93836ae824c.PNG)

On the real page I made the headline a bit smaller and the small tag to:
```css
h1, .h1 {
    font-size: 1.6em;
}
.h1 .small, .h1 small, .h2 .small, .h2 small, .h3 .small, .h3 small, h1 .small, h1 small, h2 .small, h2 small, h3 .small, h3 small {
    font-size: 65%;
}
```
